const TypesCart = {
  GET_PRODUCTS_CART_SUCCESS: 'GET_PRODUCTS_CART_SUCCESS',
  GET_PRODUCTS_CART_FAILURE: 'GET_PRODUCTS_CART_FAILURE',
  SET_CART_POPUP_SUCCESS: 'SET_CART_POPUP_SUCCESS',
  SET_CART_POPUP_FAILURE: 'SET_CART_POPUP_FAILURE',
  SET_OPEN_MODAL: 'SET_OPEN_MODAL',
  SET_CLOSE_MODAL: 'SET_CLOSE_MODAL',
  DELETE_ITEM_LIST_SUCCESS: 'DELETE_ITEM_LIST_SUCCESS',
  DELETE_ITEM_LIST_FAILURE: 'DELETE_ITEM_LIST_FAILURE',
  UPDATE_CART_POPUP_SUCCESS: 'UPDATE_CART_POPUP_SUCCESS',
  UPDATE_CART_POPUP_FAILURE: 'UPDATE_CART_POPUP_FAILURE',
  SET_MODAL_STATUS: 'SET_MODAL_STATUS',
};

export default TypesCart;
